version: "3"
services:
  mqtt:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001

  powerserver:
    build:
      context: ./webserver
      dockerfile: ./Dockerfile
    container_name: powerserver
    ports:
      - 8081:8081
    depends_on:
      - mqtt
    command: ["./powerserver", "-mqttURL=tcp://mqtt:1883"]
